### ISSUE TITLE
Google Login does not work on Android

### ISSUE THREAD

**Issue by rooswelt** [xtreamsrl/firebase-ngrx-user-management#1]
When try to login with google, opens account selection in browser, then a white page

**Comment by rams23** [comment]
Hi @rooswelt sorry for late reply. Did you see any error or log to help identify the problem?

**Comment by simplenetworks** [comment]
No error in log, I also tried to use "ionic" branch to have native login, but I have this runtime error:

`NullInjectorError: StaticInjectorError(AppModule)[ProvidersManagementEffects -> InjectionToken userManagement.config]: 
  StaticInjectorError(Platform: core)[ProvidersManagementEffects -> InjectionToken userManagement.config]: 
    NullInjectorError: No provider for InjectionToken userManagement.config!
    at NullInjector.get (http://localhost:8100/vendor.js:38445:27)
    at resolveToken (http://localhost:8100/vendor.js:40231:24)
    at tryResolveToken (http://localhost:8100/vendor.js:40157:16)
    at StaticInjector.get (http://localhost:8100/vendor.js:40020:20)
    at resolveToken (http://localhost:8100/vendor.js:40231:24)
    at tryResolveToken (http://localhost:8100/vendor.js:40157:16)
    at StaticInjector.get (http://localhost:8100/vendor.js:40020:20)
    at resolveNgModuleDep (http://localhost:8100/vendor.js:64070:29)
    at _createClass (http://localhost:8100/vendor.js:64147:32)
    at _createProviderInstance (http://localhost:8100/vendor.js:64103:26)`

Do I need to create a userManagement.config file? Where should I put it?

Thanks in advance

**Comment by rams23** [comment]
@simplenetworks I think i forgot to update the readme fot the ionic version you need to use the forRoot method of the module passing the googleWebClientId that is necessary for the native plugin: like this:

    FirebaseNgrxUserManagementModule.forRoot({googleWebClientId:''}),

Truly sorry for this
